version: "3"
services:
  db:
    container_name: animar_db
    image: mysql:8.0.24
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_go
      - MYSQL_USER=db_test
      - MYSQL_PASSWORD=password
      - TZ="Asia/Tokyo"
    #build:
    #context: .
    #dockerfile: Dockerfile_mysql
    tty: true
    #command: --default-authentication-plugin=mysql_native_password
    #command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: mysqld
    ports:
      - 13306:3306
    networks:
      - network

  web:
    container_name: animar
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_go
      - MYSQL_USER=db_test
      - MYSQL_PASSWORD=password
      - TZ="Asia/Tokyo"
    # volumes:
    #   - .:/go/src/app
    ports:
      - 8080:8080
    networks:
      - network

networks:
  network:
    driver: bridge
